### ISSUE TITLE
window.customElements.getName is not a function.

### ISSUE THREAD

**Issue by SEPPDROID** [goauthentik/authentik#22611]
### Describe the bug

Hi,

After the update to 2026.5 i noticed my flows stopped working on some older IOS devices with error:

window.customElements.getName is not a function. (In 'window.customElements.getName(o)', 'window.customElements.getName' is undefined)

They had worked this morning but I haven’t had time yet to check whether it’s an issue on my end or possibly fixable via a legacy setting, but checking MDN leads me to believe that all older Safari and WebView browsers before version 17 will be unable to render it.

If this was an explicit choice, feel free to close this. Gracefully falling back or implementing check for customElements.getName() might be more work then the small amount of environments in the wild

### How to reproduce

1. Grab a browser in IOS16 (p. Emulated)
2. Open a flow
3. Greeted with error

### Expected behavior

Flow to continue

### Deployment Method

Docker

### Version

2026.5

### Relevant log output

```shell
window.customElements.getName is not a function. (In 'window.customElements.getName(o)', 'window.customElements.getName' is undefined)
```

**Comment by pocax** [comment]
it also happened with my device IP8, ios 16

**Comment by przwr** [comment]
I got a report from one of our users about this issue. We use 2026.5.2, but the issue persists
