### ISSUE TITLE
Discord OAuth provider Role sync problem with Authentik 2026.2.2

### ISSUE THREAD

**Issue by VULGA01** [goauthentik/authentik#22175]
### Describe the bug

Hi there, I’m trying to use the Discord OAuth provider with Authentik 2026.2.2, following the official documentation here:
https://version-2026-2.goauthentik.io/users-sources/sources/social-logins/discord/

But the property mapping from the docs does not seem to work for me, especially the part that syncs Discord roles and the profile picture/avatar.

On login callback, Authentik returns a 500 error. In the logs I get:

```text
property_mapping_exception
mapping: discord-role-sync
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
line 32: guild_data = guild_response.json()
Failed to evaluate property mapping: 'discord-role-sync'
Internal Server Error: /source/oauth/callback/discord/
```

The failing code is this part from the mapping:

```python
guild_response = client.do_request("GET", guild_url, token=token)
guild_data = guild_response.json()
```

I’m not sure if something changed in Authentik 2026.2.2, in the Discord OAuth client, or in how `client.do_request(..., token=token)` works, but it looks like the response is empty or not valid JSON.

Has anyone managed to make Discord role sync + avatar/profile picture sync work with this version?

### How to reproduce

1. Deploy authentik 2026.2.2 with Docker Compose.
2. Configure a Discord OAuth source.
3. Add the property mapping from the official Discord documentation:
   https://version-2026-2.goauthentik.io/users-sources/sources/social-logins/discord/
4. Configure the mapping to sync Discord guild roles and avatar/profile picture.
5. Start a login/enrollment flow using Discord.
6. Complete the Discord OAuth authorization.
7. On callback, authentik returns a 500 error.

### Expected behavior

The Discord OAuth login/enrollment should complete successfully.

The property mapping should fetch the Discord guild member information, sync matching Discord roles to authentik groups, and import the Discord avatar/profile picture without causing a 500 error.

### Deployment Method

Docker

### Version

2026.2.2

### Relevant log output

```shell
property_mapping_exception
...
JSONDecodeError
...
Internal Server Error: /source/oauth/callback/discord/
...
status: 500
```

**Comment by dewi-tik** [comment]
https://github.com/goauthentik/authentik/issues/22367

**Comment by dewi-tik** [comment]
Can you confirm that your oauth discord app has the correct permissions?

**Comment by Benricheson101** [comment]
I'm unable to reproduce this. It looks like Discord was having API issues that day, is it working now?

https://discordstatus.com/incidents/4hpm4454hxtx

**Comment by TheConen** [comment]
I found the examples from the documentation to not handle errors very well, so I modified them a bit.
This is what I currently use for avatar/role sync and it works fine with 2026.5.2 ( I removed the base64 avatar because I don't need it, but you could just add it back):

```python
from authentik.core.models import Group

# Set these values
ACCEPTED_GUILD_ID = "YOUR_GUILD_ID" 
AVATAR_SIZE = "64"

# Generate Avatar URL
user_id = info.get("id")
avatar_hash = info.get("avatar")
avatar_url = None

if avatar_hash and user_id:
    avatar_url = (f"https://cdn.discordapp.com/avatars/{user_id}/"
                  f"{avatar_hash}.png?size={AVATAR_SIZE}")

# Check Guild Membership
member_url = f"https://discord.com/api/v10/users/@me/guilds/{ACCEPTED_GUILD_ID}/member"
user_groups = []
try:
    # Make call to Discord API
    headers = {
        "User-Agent": "Authentik-Discord-Mapping/1.0"
    }
    response = client.do_request("GET", member_url, token=token, headers=headers)
    
    if response.status_code == 200:
        # User is a member, extract roles
        guild_data = response.json()
        roles = guild_data.get("roles", [])
        
        # Get matching Authentik groups based on Discord Role IDs
        if roles:
            user_groups = Group.objects.filter(attributes__discord_role_id__in=roles)
            
    elif response.status_code == 404:
        # User is not a member of the guild - this is expected behavior
        pass
    elif response.status_code == 429:
        ak_logger.warning(f"Discord Rate Limit hit for user {info.get('username')}")
    else:
        ak_logger.info(f"Discord API returned status {response.status_code}: {response.text}")

except Exception as e:
    ak_logger.error(f"Error fetching Discord roles: {str(e)}")

# Return user data
return {
    "name": info.get("global_name") or info.get("username"),
    "attributes.discord": {
        "id": user_id,
        "username": info.get("username"),
        "email": info.get("email"),
        "avatar": avatar_hash,
        "avatar_url": avatar_url
    },
    "groups": [group.name for group in user_groups]
}
```
