### ISSUE TITLE
Migration fails with AttributeError: 'NoneType' object has no attribute 'users'

### ISSUE THREAD

**Issue by artuselias** [goauthentik/authentik#11226]
**Describe the bug**
After upgrading from Authentik 2024.6.4 to 2024.8.0 with docker compose, Authentik is unable to start.

**To Reproduce**

1. Replaced '6.4' with '8.0' in docker-compose.yml
2. docker dompose down
3. docker compose up -d

**Expected behavior**
Authentik resumes normally.

**Logs**
authentik-server:
```
=== Starting migration

Operations to perform:

  Apply all migrations: auth, authentik_blueprints, authentik_brands, authentik_core, authentik_crypto, authentik_enterprise, authentik_events, authentik_flows, authentik_outposts, authentik_policies, authentik_policies_dummy, authentik_policies_event_matcher, authentik_policies_expiry, authentik_policies_expression, authentik_policies_geoip, authentik_policies_password, authentik_policies_reputation, authentik_providers_google_workspace, authentik_providers_ldap, authentik_providers_microsoft_entra, authentik_providers_oauth2, authentik_providers_proxy, authentik_providers_rac, authentik_providers_radius, authentik_providers_saml, authentik_providers_scim, authentik_rbac, authentik_sources_ldap, authentik_sources_oauth, authentik_sources_plex, authentik_sources_saml, authentik_sources_scim, authentik_stages_authenticator_duo, authentik_stages_authenticator_sms, authentik_stages_authenticator_static, authentik_stages_authenticator_totp, authentik_stages_authenticator_validate, authentik_stages_authenticator_webauthn, authentik_stages_captcha, authentik_stages_consent, authentik_stages_deny, authentik_stages_dummy, authentik_stages_email, authentik_stages_identification, authentik_stages_invitation, authentik_stages_password, authentik_stages_prompt, authentik_stages_source, authentik_stages_user_delete, authentik_stages_user_login, authentik_stages_user_logout, authentik_stages_user_write, authentik_tenants, contenttypes, guardian, sessions

Running migrations:

  Applying authentik_providers_ldap.0004_alter_ldapprovider_options_and_more...

Adding permission 'authentik Providers.LDAP | LDAP Provider | Search full LDAP directory'

INF domain_url=null event=releasing database lock logger=lifecycle.migrate pid=181 schema_name=public timestamp=2024-09-05T06:52:27.690812

Failed to read config file: ./lifecycle/gunicorn.conf.py

Traceback (most recent call last):

  File "/ak-root/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 110, in get_config_from_filename

    spec.loader.exec_module(mod)

  File "<frozen importlib._bootstrap_external>", line 995, in exec_module

  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed

  File "/lifecycle/gunicorn.conf.py", line 154, in <module>

    run_migrations()

  File "/lifecycle/migrate.py", line 112, in run_migrations

    execute_from_command_line(["", "migrate_schemas"])

  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line

    utility.execute()

  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute

    self.fetch_command(subcommand).run_from_argv(self.argv)

  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv

    self.execute(*args, **cmd_options)

  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute

    output = self.handle(*args, **options)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/ak-root/venv/lib/python3.12/site-packages/django_tenants/management/commands/migrate_schemas.py", line 63, in handle

    executor.run_migrations(tenants=[self.PUBLIC_SCHEMA_NAME])

  File "/ak-root/venv/lib/python3.12/site-packages/django_tenants/migration_executors/standard.py", line 11, in run_migrations

    run_migrations(self.args, self.options, self.codename, self.PUBLIC_SCHEMA_NAME)

  File "/ak-root/venv/lib/python3.12/site-packages/django_tenants/migration_executors/base.py", line 59, in run_migrations

    migrate_command_class(stdout=stdout, stderr=stderr).execute(*args, **options)

  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute

    output = self.handle(*args, **options)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/base.py", line 107, in wrapper

    res = handle_func(*args, **kwargs)

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/ak-root/venv/lib/python3.12/site-packages/django/core/management/commands/migrate.py", line 356, in handle

    post_migrate_state = executor.migrate(

                         ^^^^^^^^^^^^^^^^^

  File "/ak-root/venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 135, in migrate

    state = self._migrate_all_forwards(

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/ak-root/venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards

    state = self.apply_migration(

            ^^^^^^^^^^^^^^^^^^^^^

  File "/ak-root/venv/lib/python3.12/site-packages/django/db/migrations/executor.py", line 252, in apply_migration

    state = migration.apply(state, schema_editor)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/ak-root/venv/lib/python3.12/site-packages/django/db/migrations/migration.py", line 132, in apply

    operation.database_forwards(

  File "/ak-root/venv/lib/python3.12/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards

    self.code(from_state.apps, schema_editor)

  File "/authentik/providers/ldap/migrations/0004_alter_ldapprovider_options_and_more.py", line 26, in migrate_search_group

    provider.search_group.users.using(db_alias).all().values_list("pk", flat=True)

    ^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: 'NoneType' object has no attribute 'users'

warning error=exit status 1 event=gunicorn process died, restarting logger=authentik.router timestamp=2024-09-05T06:52:28Z

ERR error=exit status 1 event=gunicorn failed to start, restarting logger=authentik.router timestamp=2024-09-05T06:52:28Z
```

**Version and Deployment (please complete the following information):**

-   authentik version: 2024.8.0
-   Deployment: docker compose

**Additional context**
docker-compose.yml:
```
---

services:
  postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${PG_PASS:?database password required}
      POSTGRES_USER: ${PG_USER:-authentik}
      POSTGRES_DB: ${PG_DB:-authentik}
    env_file:
      - .env
  redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis:/data
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.8.0}
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
    env_file:
      - .env
    ports:
      - "${COMPOSE_PORT_HTTP:-9000}:9000"
      - "${COMPOSE_PORT_HTTPS:-9443}:9443"
    depends_on:
      - postgresql
      - redis
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2024.8.0}
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: redis
      AUTHENTIK_POSTGRESQL__HOST: postgresql
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
    env_file:
      - .env
    depends_on:
      - postgresql
      - redis

volumes:
  database:
    driver: local
  redis:
    driver: local
```

**Comment by BeryJu** [comment]
Fixed by https://github.com/goauthentik/authentik/pull/11170, will be released in 2024.8.1, you can use ghcr.io/goauthentik/dev-server:gh-version-2024.8 in the meantime
