### ISSUE TITLE
AttributeError: 'TenantAwareScheduleEntry' after upgrading from 2025.4.2 to 2025.6.0

### ISSUE THREAD

**Issue by timothyscherer** [goauthentik/authentik#14917]
Upgrading from 2025.4.2 to 2025.6.0 produced the following on `authentik-worker-1`. When this happens, the authentik webpage just remains blank. For now I have successfully reverted back to 2025.4.2.

```py
Traceback (most recent call last):
  File "/ak-root/.venv/lib/python3.13/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
    ~~~~~~~~^^
  File "/ak-root/.venv/lib/python3.13/site-packages/celery/beat.py", line 719, in run
    self.service.start(embedded_process=True)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/ak-root/.venv/lib/python3.13/site-packages/celery/beat.py", line 644, in start
    interval = self.scheduler.tick()
  File "/ak-root/.venv/lib/python3.13/site-packages/celery/beat.py", line 354, in tick
    self.apply_entry(entry, producer=self.producer)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/authentik/tenants/scheduler.py", line 20, in apply_entry
    if entry.tenant_schemas is None:
       ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'TenantAwareScheduleEntry' object has no attribute 'tenant_schemas'
```

-   authentik version: [e.g. 2025.6.0]
-   Deployment: docker-compose
