### ISSUE TITLE
Webauthn on iOS and Mac broken with latest release. 

### ISSUE THREAD

**Issue by yeyeoke** [goauthentik/authentik#3050]
**Describe the bug**
Using Webauthn on Safari on Mac OS and iOS seems to have been broken. It worked on 2022.5 but not on 2022.6.1.

**To Reproduce**
1. Create a passwordless flow
2. Go to auth.company.com
3. Select passwordless flow.
4. Get a "Whoops!
Something went wrong! Please try again later."

**Expected behavior**
In 2022.5 everything just worked. 

**Logs**
<details>
    <summary>Stacktrace from authentik</summary>

```
Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 328, in post
    stage_response = self.current_stage_view.post(request, *args, **kwargs)
  File "/authentik/stages/authenticator_validate/stage.py", line 271, in post
    res = super().post(request, *args, **kwargs)
  File "/authentik/flows/stage.py", line 120, in post
    return self.challenge_valid(challenge)
  File "/authentik/stages/authenticator_validate/stage.py", line 380, in challenge_valid
    self.logger.debug("Set user from user-less flow", user=webauthn_device.user)
'dict' object has no attribute 'user'
```
</details>

**Version and Deployment (please complete the following information):**
- authentik version: 2022.6.1
- Deployment: docker-compose

**Additional context**
I've tried deleting the old device in Authentic and registering a new, still doesn't work. I've tried clearing Safaris cache on both iPhone and Macbook.

**Comment by yeyeoke** [comment]
Something is still not working quite right in 2022.6.2. 

If I open auth.company.com, and try to sign-in using webauthn, it gives me an error message. If I then try to reload the page, and once again sign-in using webauthn it works. 



Traceback (most recent call last):
  File "/authentik/flows/views/executor.py", line 328, in post
    stage_response = self.current_stage_view.post(request, *args, **kwargs)
  File "/authentik/stages/authenticator_validate/stage.py", line 271, in post
    res = super().post(request, *args, **kwargs)
  File "/authentik/flows/stage.py", line 97, in post
    if not challenge.is_valid():
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 426, in run_validation
    value = self.to_internal_value(data)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/serializers.py", line 485, in to_internal_value
    validated_value = validate_method(validated_value)
  File "/authentik/stages/authenticator_validate/stage.py", line 95, in validate_webauthn
    self.device = validate_challenge_webauthn(
  File "/authentik/stages/authenticator_validate/challenge.py", line 123, in validate_challenge_webauthn
    raise Http404()

**Comment by Cookie-Monster-Coder** [comment]
Same issue
